[project]
name = "balancio-sim"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
platforms = ["win-64"]

[dependencies]
python = ">=3.10.0,<3.11"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=61.0.0,<61.1"
numpy = ">=1.26.4,<1.27"
scipy = ">=1.14.0,<1.15"
casadi = ">=3.6.3,<3.7"

[activation]
scripts = ["install/setup.bat"]
