[project]
name = "balancio-sim"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = ">=3.10.0,<3.11"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=61.0.0,<61.1"
numpy = ">=1.26.4,<1.27"
scipy = ">=1.14.0,<1.15"
casadi = ">=3.6.3,<3.7"
ruff = ">=0.5.5,<0.6"
mypy = ">=1.11.1,<2"

[tasks]
"lint" = "pixi run ruff check . && pixi run ruff format --check . && pixi run mypy --explicit-package-bases ."
"format" = "pixi run ruff check --fix . && pixi run ruff format ."

[activation]
scripts = ["install/setup.sh"]

[target.win-64.activation]
scripts = ["install/setup.bat"]
